name: Build and Push to Docker Registry

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  GIT_REF: ${{ github.head_ref || github.ref_name }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_URL }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  docker:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build and push
        id: build_and_push
        run: ./.github/scripts/build_and_push.sh
        env:
          DOCKER_IMAGE_NAME: "registry.digitalocean.com/karpatkey/defi-repertoire"
          DOCKERFILE: "./Dockerfile"

  update-deployment:
    needs: docker
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - name: Update Deployment
        run: |
          LATEST_IMAGE=$(cat latest_image.txt)
          kubectl set image deployment/defi-repertoire -n defi-repertoire defi-repertoire=${LATEST_IMAGE}

