name: Build and Push to Docker Registry


on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: registry.digitalocean.com/karpatkey/defi_repertoire
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}
            latest

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile

  update-deployment:
    needs: docker
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - run: kubectl delete pod -n defi_repertoire -l app=defi_repertoire --force
